### ISSUE TITLE
Make typechecker work on more advanced language constructs

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/Alpaca#11]

**Comment by TrikkStar** [comment]
@Skiadas, when I'm trying to typecheck our tuples and lists I'm trying to put the types in a list using the :: operator, however I'm getting the following error: 
`This variant expression is expected to have type expT
the constructor :: does not belong to type exprT` 
Why am I not able to add my exprTs to a list this way?

**Comment by skiadas** [comment]
Ok let's look at your TupleC code:
```
| TupleC t ->
    (match t with
    | head :: tail -> (typecheck env head) :: (typecheck env tail)
    | [] -> [])
```

Indeed `t` is a `exprC list`. So `head` is an `exprC`, and `tail` is an `exprC list`. So first of all you will have a problem with `typecheck env tail`, because typecheck expects an `exprC` and you are giving it a whole list of `exprC`s.

Second, you are trying to return a list of `exprT`s. That's not going to work, as the return of the typeckeck needs to be a single `exprT`.

You probably want to start with doing a List.map of the typechecker over the list of expressions. This gives you back a list of types. You have to then figure out how this list of types relates to the information you need to return. But you can't return a list of types, you must return a single `exprT` (which could of course be one of the variants that contains other `exprT`s in it).

Also for typechecking, the work you have to do in the ListC is very different from the work you have to do for tuples.

**Comment by TrikkStar** [comment]
Why does the typechecking for lists differ for that of tuples?

**Comment by skiadas** [comment]
Because the tuple `(3, true, "hi")` would have type `int * bool * string`, while a list `[3, true, "hi"]` would be a typecheck error. All elements in the list are required to be of the same type.

**Comment by TrikkStar** [comment]
ok, that makes sense.

**Comment by TrikkStar** [comment]
@skiadas 
So I'm trying to make a function, `listType`, that will go through a list and determine if all elements of the list are of the same type. I've thought of recursion and the `List.exists` method but can't seem to determine a solution that will work effectively. Any suggestions on how to do this?

**Comment by skiadas** [comment]
You don't need recursion but yeah you'll want to call `List.forall` probably. First of all, start with a `List.map`, to obtain a list of the types for each expression in the list. Then you have to distinguish two cases, via a match on the type list:

- If the list is non-empty, then you can take the first type and compare it to all the remaining types, using `List.forall` for the traversal.
- If the list is empty, that means you had an empty list to begin with. You need to specify for it some type, and the problem is that you don't know what type is right, yet. Because if you later prepend an integer to the list, the type should become int. So what you need to do is create a new type, call it "AnyT" or something like that, then use that as the type for the contents of an empty list. You will then need to think of what should happen at various list operations, regarding a "ListT AnyT" and typechecking.

**Comment by TrikkStar** [comment]
So I'm confused why this line works in `valToString` :
`| head :: rest -> valToString head ^ ", " ^ valToString (List rest)`
but a simmalar line doesn't work in `typToString`:
`| head :: rest -> typToString head ^ " * " ^ typToString (List rest))`

**Comment by skiadas** [comment]
My guess is that it's the `ListT` case that is failing? You keep forgetting that the type stored in a `ListT` is a single type, not a list of types. So you cannot match it to a list, which I am guessing is the error you are getting?

By the way there are far better ways to do those cases involving processing of lists, without recursively calling the method. You can `List.map` to get the corresponding strings, then feed that into `String.concat` (see http://caml.inria.fr/pub/docs/manual-ocaml/libref/String.html).

**Comment by TrikkStar** [comment]
@skiadas So I'm getting two errors which appear to contradict one another. 
When I have the folloing line: `| FunC (str, lst, x) -> FunT (typecheck env x) (typecheck env x)` I get the error `syntax error characters 49-50`.
But when I change the line to `| FunC (str, lst, x) -> FunT ((typecheck env x) (typecheck env x))` I get an error saying that FunT takes two arguments instead of one. This second error makes sense but I don't understand what's causing the first one.

**Comment by skiadas** [comment]
Hm I'm not sure what that error is for, but first off all the code I'm seeing in your file tries to pattern match FunC with only two arguments instead of the 3 you mentioned here, which is more correct.

Still, you shouldn't expect that to give you the correct answer, even if it did work. The first part of FunT is for type of input, and the second is for type of output. The type of input is effectively the "type" of the "str" part, which you now need to know at this point. Your function declarations therefore will need to actually include a type for the function argument, and your parser will need to be able to read these types. Then that type is what goes in the first part of FunT, while typechecking "x", which is the body of the function, in an appropriately extended environment will give you the correct right-hand side.

**Comment by TrikkStar** [comment]
I'm trying to typecheck let statements, but I'm getting a type error in evaluate, `line 198 characters 65-66. This expression has type 'a list ref but an expression was expected of type (string * exprtT) list`
I feel like I'm not correctly returning my LetT but am not sure how I need to return it.

**Comment by skiadas** [comment]
Look at how LetC  was done, this part uses the wrong "environment": `bind str typ_e1 global_ref` since `global_ref` is not an actual environment, but a ref to one. You need to dereference it.

Also you should not be returning a `LetT`. There should not be a `LetT`.

By the way, you cannot use the same `global_ref` for both interpretation and typechecking. You'll need two refs, one containing dynamic environments and one containing static environments.

**Comment by TrikkStar** [comment]
So which ref should be static and which should be dynamic? Also how do I dereference global_ref?
If i'm not retuning a LetT then what should I be returning instead?

**Comment by skiadas** [comment]
The static would be used for the typechecking, the dynamic for interpreting (this is week 1 stuff). For dereferencing look up about refs in OCAML, again this is stuff we�ve covered.

A let expression should typecheck to whatever the type of the main expression in it is. So if you are doing �let x = e1� it should typecheck to the type of e1, if you are doing �let x = e1 in e2� it should typecheck to the type of e2.

Haris Skiadas
Hanover College
