### ISSUE TITLE
Comments don't correctly end with `*)`

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/Alpaca#12]
When in the interpreter, entering a comment starting with `(*` and ending with `*)` does not work as intended. It doesn't appear that the ending of comments are read since multiple lines can have a `;;` but the command won't execute.

**Comment by TrikkStar** [comment]
@Skiadas, should we be passing our comments as a `token lexbuf`, or is there another type of token we should be using?

**Comment by skiadas** [comment]
Yeah that should work if you want the comments to basically be ignored (and that's fine). Is it not working?

**Comment by TrikkStar** [comment]
It's not working no. When I start, and supposedly end, a comment I can't seem to get the line to be read. I'll put in a `;;` but it will just go to the next line like I hadn't ended the line yet.

**Comment by skiadas** [comment]
Hm this is really tricky. What you want is actually this expression:
```
let comment = "(*" ([^ '*']| '*' [^ ')'])* "*)"
```

What is happening is this: You have put `_*` in the match. This will try to match as much as it can, it will not simply stop because it can complete it via `*)`. So it keeps waiting for more and more and more input, in search of a longer match, until we terminate the input, which doesn't really happen. The above regexp will allow as contents anything that is: either not a `*`, or a `*` that is followed by anything that is not a `)`. In other words it will keep on matching until it finds a `*)` and it will not match that.

**Comment by TrikkStar** [comment]
OK, I figured it was a problem with the regex but wasn't sure how to fix it.
