### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/Alpaca#8]
@skiadas @DaltonMcc  When I try to compile the types files I'm receiving the following error: 
`File "types.mli", line 41, characters 22-26:  
Error: The type constructor list expects 1 argument(s), 
          but is here applied to 0 argument(s)`

Looking at that line bring me to where we're defining our list value, but I don't see what's wrong with it.

**Comment by skiadas** [comment]
"list" by itself is not a valid type. You can have "int list", "string list", "(int * int) list" etc. You have to specify the type for the elements of the list.

By the way, your language's List type should only have one type in it, describing the type of the contents. So that should NOT say "list" there, it should have a type there. The Tuple needs a list of types.

**Comment by TrikkStar** [comment]
So I'm getting the same error still, but this time it's in `parser.mli`
"File "parser.mli", line 5, characters 13-17:
Error: The type constructor list expects 1 argument(s),
       but is here applied to 0 argument(s)"

**Comment by skiadas** [comment]
You've told it that LIST is to contain a value "list":
`%token <list> LIST`
and a similar thing for tuples. "list" by itself is NOT a type. `'a list` is a type. You must put in front of the word list the type of the elements it is supposed to contain, otherwise it is not a valid type. So `int list`, `exprS list`, `exprT list` are valid types (of course you need a specific one in this instance).

**Comment by skiadas** [comment]
Btw you have some shift/reduce conflicts in your grammar (you can see it when you do ocamlyacc). You'll want to resolve them. A lot of them are related to  LET and VARIABLE not having precedence rules. Basically the parser doesn't know what it should do if it encounters "LET x + y". Btw what are the "LET expr" and "VARIABLE expr" rules meant to represent? I'm not sure what to make out of a statement like "LET 5"

**Comment by TrikkStar** [comment]
I guess I'm still unsure how to correctly make the token for the list and tuple types. I'm currently getting the error:
`File "parser.mli", line 5, characters 13-18:
Error: Unbound type constructor exprS`  
I'm unsure at this point what type I'm supposed to make the list, I tried just expr but got the same error.

**Comment by TrikkStar** [comment]
think I figured that issue out, changed the type to `<Types.exprS list>`
